language: node_js

notifications:
  email:
    - josh.rossi@alphapoint.com

install:
  - npm install

before_script:
  - echo before...

script:
  - npm run build
  - npm run publish

after_script:
  - echo after...
