language: node_js

notifications:
  email:
    - josh.rossi@alphapoint.com

script:
  - npm run build
  - $NPM_TOKEN

deploy:
  provider: npm
  edge: true
  skip_cleanup: true
  email: "josh.rossi@alphapoint.com"
  api_key: $NPM_TOKEN
