language: node_js

notifications:
  email:
    - josh.rossi@alphapoint.com

script:
  - npm version patch -m "Bumping to version  %s"

before_deploy:
  - npm run build

deploy:
  provider: npm
  edge: true
  skip_cleanup: true
  email: "josh.rossi@alphapoint.com"
  api_key: $NPM_TOKEN
